[package]
name = "curvedit"
version = "0.1.0"
edition = "2021"

[dependencies]
fso_curves = { git = "https://github.com/BMagnu/fso-tables-rust.git" }
fso_tables = { git = "https://github.com/BMagnu/fso-tables-rust.git" }